### ISSUE TITLE
node red crashed

### ISSUE THREAD

**Issue by mrnik** [namgk/node-red-contrib-pythonshell#7]
Running your example on windows installed node-red and Python2.7 returns the following-

6 Mar 14:04:14 - [red] Uncaught Exception:
6 Mar 14:04:14 - Error: spawn python ENOENT
    at _errnoException (util.js:1022:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)

**Comment by mrnik** [comment]
Also this message appears

6 Mar 15:41:59 - [red] Uncaught Exception:
6 Mar 15:41:59 - Error: listen EADDRINUSE :::8000
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1351:14)
    at listenInCluster (net.js:1392:12)
    at Server.listen (net.js:1476:7)
    at Server.listen.Server.attach (C:\Users\marios.LEFH\.node-red\node_modules\
socket.io\lib\index.js:228:9)
    at new socketIoConfig (C:\Users\marios.LEFH\.node-red\node_modules\node-red-
contrib-socketio\socketio.js:26:7)
    at createNode (C:\Users\marios.LEFH\AppData\Roaming\npm\node_modules\node-re
d\red\runtime\nodes\flows\Flow.js:305:18)
    at Flow.start (C:\Users\marios.LEFH\AppData\Roaming\npm\node_modules\node-re
d\red\runtime\nodes\flows\Flow.js:67:31)
    at start (C:\Users\marios.LEFH\AppData\Roaming\npm\node_modules\node-red\red
\runtime\nodes\flows\index.js:307:29)

**Comment by namgk** [comment]
probably a Node-RED issue.
